### ISSUE TITLE
tutorial_1: RuntimeError: leaf variable has been moved into the graph interior

### ISSUE THREAD

**Issue by AdaUchendu** [YunseokJANG/l2l-da#1]
When I run this line in the tutorial_1 below:
I get the following error: RuntimeError: leaf variable has been moved into the graph interior

seq_pgd_attack_obj = aa.PGD(model, normalizer, sequential_threat, seq_attack_loss)
seq_perturbation = seq_pgd_attack_obj.attack(examples, labels, num_iterations=20, signed=False, 
                                             optimizer=optim.Adam, 
                                             optimizer_kwargs={'lr': 0.001}, verbose=True)

Everything else in all the tutorials works and I checked to make sure I have the appropriate Pytorch version as well. 

The error seems to have originated from:
--> line 353             torch.autograd.backward(loss) in adversarial_attacks.py

**Comment by YunseokJANG** [comment]
First of all, thanks for the report. However, frankly, I failed to reproduce the same issue; I guess some configuration may not match in your setting since some other groups already tested their method based on this codebase. So, I recommend rechecking every package version first. 

If you still face the same issue, even the environment is exactly same (clean-reinstalled), then one thing that I can suggest, based on the error message you've shared, is to check/debug the error by printing out `.is_leaf' for each variable (ref: https://discuss.pytorch.org/t/leaf-variable-was-used-in-an-inplace-operation/308 ). I hope it works.

Regards,
- Yunseok
