### ISSUE TITLE
Black-box 

### ISSUE THREAD

**Issue by Nono-404** [YunseokJANG/l2l-da#2]
How to implement black box attacks and defenses in your code？
Thanks.

**Comment by YunseokJANG** [comment]
Hi, @Lee-Yuxin 

First of all, thank you for your interest in our work. This repository currently does not include the code for the black box attack (and I've lost the detail due to the time gap from the release), but I believe you can add it on your own. First of all, as far as I remember, to perform an L2L-DA attack on a pre-trained classifier, you first need to [feed 'False' in is_train arg](https://github.com/YunseokJANG/l2l-da/blob/07c64bc1262d1ffb6a02512353852d0e55f25b3f/main.py#L39) and make the tester properly load your checkpoint ([1](https://github.com/YunseokJANG/l2l-da/blob/master/adv_defence/classifier_tester.py#L56), [2](https://github.com/YunseokJANG/l2l-da/blob/master/adv_defence/models.py#L265), [3](https://github.com/YunseokJANG/l2l-da/blob/07c64bc1262d1ffb6a02512353852d0e55f25b3f/adv_defence/helper.py#L159)). Once it is properly loaded, then you can perform an attack with our L2L-DA generator. For the black-box, I first saved all the generated attacks and then tested the saved items afterwards. You can also perform other attacks used in our paper via [mister_ed](https://github.com/revbucket/mister_ed) or any framework that you prefer. I hope it helps to implement your own. 

Regards,
Yunseok Jang
